name: build_radiodelay

on:
  push:
    branches: [ test-github-actions ]

jobs:
  windows:
    runs-on: windows-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    defaults:
      run:
        shell: C:\msys64\usr\bin\bash.exe --login -eo pipefail "{0}"
    env:
      MSYSTEM: MINGW64
      CHERE_INVOKING: 1
    steps:
    - uses: actions/checkout@v2
    - name: Install packages
      run: pacman -S --needed --noconfirm mingw-w64-x86_64-fltk mingw-w64-x86_64-make
    - name: Code sign certificate
      run: base64 -d -i <<< "${{ secrets.CODE_SIGN_CERTIFICATE }}" > daansystems.pfx
    - name: Check path
      run: echo $PATH
    - name: Check g++
      run: type g++
    - name: Make
      run: CODE_SIGN_CERTIFICATE_PASSWORD=${{ secrets.CODE_SIGN_CERTIFICATE_PASSWORD }} make windows-signed
   