name: windows_x64_msys2

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest
    defaults:
      run:
        shell: bash.exe --login -eo pipefail "{0}"
    env:
      MSYSTEM: MINGW64
      CHERE_INVOKING: 1
    steps:
    - uses: actions/checkout@v2
    - name: uname
      run: uname -a
    - name: pacman
      run: pacman -S --noconfirm mingw-w64-x86_64-fltk
    - name: make
      run: make release
